# Workflow to generate pages site from Notes

name: Notes CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate site navigation
        run: ./navgen.py site/Notes site/nav

      - name: Build sphinx website
        run: make html

      - name: Fix permissions
        run: chmod -R +rX "build/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "build/"

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
