# Workflow to generate pages site from Notes

name: Notes CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate site navigation
        run: ./navgen.py site/Notes site/nav

      - name: Build sphinx website
        run: make html
